# Google Analytics
google_analytics:
  measurement_id: G-XXXXXXXXXX # 后续可以替换为真实的 GA4 ID

# 百度统计
baidu_analytics: # 后续可以替换为真实的百度统计 ID

# 访问统计
busuanzi_count:
  enable: true
  site_uv: true
  site_uv_header: 访客数
  site_uv_footer: 人
  site_pv: true
  site_pv_header: 总访问量
  site_pv_footer: 次
  page_pv: true
  page_pv_header: 阅读量
  page_pv_footer: 次
